config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "products#index"
  resources :shopping_carts, only: [:create,:destroy, :update], controller: 'shopping_carts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :shopping_cart, dependent: :destroy
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @shopping_cart = ShoppingCart.all.includes(:product)
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController

  def destroy
    @item_cart = ShoppingCart.find_by(product_id: params[:id])
    @shopping_cart = ShoppingCart.all.includes(:product)
    @product = Product.find(@item_cart.product_id)
    if @item_cart.destroy
      respond_to do |format|
        format.turbo_stream do
        render turbo_stream:
        [
          turbo_stream.replace("cart_#{@item_cart.product_id}",
            partial: 'shared/add_cart',
            locals: {product_cart: @product}),
          turbo_stream.replace("shopping_cart_total_price",
            partial: 'shared/shopping_cart/shopping_total_price',
            locals: {shopping_cart: @shopping_cart}),
          turbo_stream.replace("shopping_cart_items",
            partial: 'shared/shopping_cart/shopping_cart_items',
            locals: {shopping_cart: @shopping_cart}),
        ]
        end
      end
    end
  end

  def create
    @item_cart = ShoppingCart.new(shopping_cart_params)
    @shopping_cart = ShoppingCart.all.includes(:product)
    @product = Product.find(@item_cart.product_id)
    if @item_cart.save
      respond_to do |format|
        format.turbo_stream do
         render turbo_stream:
         [
          turbo_stream.replace("cart_#{@item_cart.product_id}",
            partial: 'shared/add_cart',
            locals: {product_cart: @product}),
          turbo_stream.replace("shopping_cart_total_price",
            partial: 'shared/shopping_cart/shopping_total_price',
            locals: {shopping_cart: @shopping_cart}),
          turbo_stream.replace("shopping_cart_items",
            partial: 'shared/shopping_cart/shopping_cart_items',
            locals: {shopping_cart: @shopping_cart}),
         ]
        end
      end
    end
  end

  def update
    @shopping_cart = ShoppingCart.find_by(product_id: params[:product_id])
    @shopping_carts= ShoppingCart.all.includes(:product)
    case params[:change_quantity]
    when "-"
      @shopping_cart.quantity -= 1
    when "+"
      @shopping_cart.quantity += 1
    end
    if @shopping_cart.update(quantity: @shopping_cart.quantity)
      respond_to do |format|
        format.turbo_stream do
        render turbo_stream:
        [
          turbo_stream.replace("shopping_cart_total_price",
            partial: 'shared/shopping_cart/shopping_total_price',
            locals: {shopping_cart: @shopping_carts}),
          turbo_stream.replace("shopping_cart_items",
            partial: 'shared/shopping_cart/shopping_cart_items',
            locals: {shopping_cart: @shopping_carts}),
        ]
        end
      end
    end
  end

  private
  def shopping_cart_params
    params.require(:item_cart).permit(:quantity, :product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title GOBackend
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    = stylesheet_link_tag "app.css"
    = stylesheet_link_tag "app_shop.css"
    = stylesheet_link_tag "app_card.css"

  body
    div class="main__content"
      = yield
    / = javascript_include_tag 'app.js'

app/views/products/index.html.slim
    div class="app__card"
        div class="app__card__top"
            div class="app__card__top__logo"
                img src="/assets/nike.png" alt=""
            div class="app__card__title" Our Products
        div class="app__card__body"
            - @products.find_each do |product|
                div class="app__shop__item" id="#{product.id}"
                    div class="app__shop__item__img" style="background-color: #{product.color}"
                        img src="#{product.image}" alt=""
                    div class="app__shop__item__name" #{product.name}
                    div class="app__shop__item__description" #{product.description}
                    div class="app__shop__item__bottom"
                        div class="app__shop__item__price" $#{product.price}
                        = render partial: "shared/add_cart", locals: {product_cart: product}
    div class="app__card"
        div class="app__card__top"
            div class="app__card__top__logo"
                img src="assets/nike.png" alt=""
        div class="app__card__title"
            | Your Carts
            = render partial: "shared/shopping_cart/shopping_total_price", locals: {shopping_cart: @shopping_cart}

        div class="app__card__body"
            = render partial: "shared/shopping_cart/shopping_cart_items", locals: {shopping_cart: @shopping_cart}

app/views/shared/_add_cart.html.slim
    = turbo_frame_tag "cart_#{product_cart.id}" do
        - if product_cart.shopping_cart.nil?
            form action="#{shopping_carts_path}" method="post" accept-charset="UTF-8"
                input name="authenticity_token" type="hidden"
                input type="hidden" name="item_cart[quantity]" id="quantity" value="1"
                input type="hidden" name="item_cart[product_id]" id="product_id" value="#{product_cart.id}"
                button type="submit" class="app__shop__item__button"
                    p ADD TO CART

        - else
            div class="app__shop__item__button app__inactive"
                div class="app__shop__item__button__cover"
                    div class="app__shop__item__button__check__cover"

app/views/shared/shopping_cart/_edit_quantity.html.slim
        = turbo_frame_tag "quantity_product_id_#{cart_item.product_id}"
            div class="app__cart__item__count__number"#{cart_item.quantity}

app/views/shared/shopping_cart/_shopping_cart_change_quantity.html.slim
        form action="#{shopping_carts_path}/#{cart_item.product_id}" method="post" accept-charset="UTF-8" class="form_quantity"
            = hidden_field_tag :authenticity_token, form_authenticity_token
            - if action == '-' && cart_item.quantity == 1
                input type="hidden" name="_method" value="delete"
            - else
                input type="hidden" name="_method" value="patch" autocomplete="off"
                input name="product_id" value="#{cart_item.product_id}" type="hidden"
                input name="change_quantity" value="#{action}" type="hidden"
            button type="submit" class="app__cart__item__count__button button__action"#{action}

app/views/shared/shopping_cart/_shopping_cart_items.html.slim
    = turbo_frame_tag "shopping_cart_items"
        - if shopping_cart.nil?
            div class="app__cart__empty"
                    p class="app__cart__empty__text" Your cart is empty
        - else
            - shopping_cart.find_each do |cart_item|
                div class="app__cart__item"
                    div class="app__cart__item__left cartItemLeft"
                        div class="app__cart__item__image cartItemImage" style="background-color: #{cart_item.product.color};"
                            div class="app__cart__item__image__block"
                                img src="#{cart_item.product.image}"
                                    alt=""
                    div class="app__cart__item__right cartItemRight"
                        div class="app__cart__item__name cartItemName" #{cart_item.product.name}
                        div class="app__cart__item__price cartItemPrice" $#{cart_item.product.price}
                        div class="app__cart__item__action cartItemActions"
                            div class="app__cart__item__count cartItemCount"
                                = render partial: "shared/shopping_cart/shopping_cart_change_quantity", locals: {cart_item: cart_item, action: "-"}
                                = render partial: "shared/shopping_cart/edit_quantity", locals: {cart_item: cart_item}
                                = render partial: "shared/shopping_cart/shopping_cart_change_quantity", locals: {cart_item: cart_item, action: "+"}
                            form action="#{shopping_carts_path}/#{cart_item.product_id}" method="post" class="form_quantity"
                                input type="hidden" name="_method" value="delete"
                                button type="submit" class="app__cart__item__remove cartItemRemove button__action"
                                    img src="/assets/trash.png" alt=""
                                = hidden_field_tag :authenticity_token, form_authenticity_token

app/views/shared/shopping_cart/_shopping_total_price.html.slim
    = turbo_frame_tag "shopping_cart_total_price"
        - total_price = 0
        - shopping_cart.find_each do |item_cart|
            - total_price += item_cart.product.price * item_cart.quantity
        span class="app__card__title__amount" $#{total_price.round(2)}